# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CookingApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CookingApp
  pod 'AlamofireImage'
  pod 'Parse'
  pod 'MessageInputBar'

  target 'CookingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CookingAppUITests' do
    # Pods for testing
  end

end
